name: Cleanfree config server CI with gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./src/main/resources/application.yml
        env:
          spring.cloud.config.server.git.username: ${{ secrets.GIT_USERNAME }}
          spring.cloud.config.server.git.password: ${{ secrets.GIT_PASSWORD }}
          encrypt.key: ${{ secrets.ENCRYPT_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cleanfree-config-server:latest -f Dockerfile .

      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cleanfree-config-server:latest

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: cleanfree-runner

    steps:
      - name: Pull image from docker hub
        run: |
          sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cleanfree-config-server:latest

      - name: Check if container is running
        id: check-container
        run: |
          if sudo docker ps -a | grep -q cleanfree-config-server; then
            echo "config-server-running=true" >> $GITHUB_OUTPUT
          else
            echo "config-server-running=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop & remove docker container
        if: steps.check-container.outputs.config-server-running == 'true'
        run: |
          sudo docker stop cleanfree-config-server
          sudo docker rm cleanfree-config-server

      - name: Docker run new container
        run: sudo docker run -d --name cleanfree-config-server -p 8071:8071 --net cleanfree-network ${{ secrets.DOCKERHUB_USERNAME }}/cleanfree-config-server:latest

      - name: Delete old docker image
        run: sudo docker system prune -f
